#:schema node_modules/wrangler/config-schema.json
name = "worst-counter5"
main = "src/index.ts"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]
services = [{ binding = "SELF", service = "worst-counter" }]

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "worst-counter-d1"
database_id = "0585790f-6967-4c63-9fa0-1fb69e1d0ac5"
